### ISSUE TITLE
Auto-validate models on instantiation?

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#31]
Consider auto-checking things like that the keys of the symbol_mappings are valid canonical names for known properties

**Comment by mkhorton** [comment]
Some validation already happens when the graph is assembled -- if the names aren't valid, it will fail when trying to create the edges, which is just a consequence of using an Enum type to store all the valid properties.

It's a good idea to add more validation to the model init though, we should do that.

**Comment by montoyjh** [comment]
This doesn't happen on instantiation, but using the command-line interface (e. g. `propnet validate -n MODEL_NAME`) or the unit tests validate that the model evaluation will work, which necessarily assigns the output to a propertied quantity.
