### ISSUE TITLE
use of symbols rather than canonical names could be confusing later on

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#33]
Let's say I have 3 known properties with canonical names:
- dielectric_constant = 4
- bulk_modulus = 2
- shear_modulus = 1

There are 2 different models. One of them calls the bulk modulus as "B" and another one decides to call the bulk modulus as "K". Thus, to use model 1 you pass in {"B": 2} whereas to use model to you pass in {"K": 2}. Yes, these can be auto-converted by reversing the symbol_mapping, but you can see how it gets a little awkward versus just passing in {"bulk_modulus": 2} for both models

**Comment by computron** [comment]
similarly, I can imagine someone inadvertently passing in the wrong parameter due to overloading of symbols. e.g., they know bulk modulus as K and they start passing in {"K": 2} to every model even though K might represent something completely different in other models - in this case the code would return a result, just nothing physical / correct

**Comment by mkhorton** [comment]
The idea of using symbols was just to make it easier to type long, unwieldy-looking equations.

These are strictly used only inside the model class, not in the graph, so (as currently coded) the models simply cannot have the 'wrong' connections. However,

> Thus, to use model 1 you pass in {"B": 2} whereas to use model to you pass in {"K": 2} ... but you can see how it gets a little awkward versus just passing in {"bulk_modulus": 2} for both models

This is very true if you want to call the models individually, i.e. without having the graph solve them. Sounds like a good idea to change the `evaluate` method to use the property names rather than the symbols.

**Comment by mkhorton** [comment]
I remembered why this decision was made ... it was so that you could have multiple inputs of the same property type into the model, then different symbols could be used to distinguish between them (this is only relevant for models that take more than one material as input). Closing this for now, might come back to it in the future.
