### ISSUE TITLE
In the figure with the Data Layer and Logic Layer, why are there arrows pointing from a PropertyType (dark blue) to Property (aqua)?

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#36]
Looks like a reverse connection? PropertyTypes don't have Properties do they?

**Comment by computron** [comment]
Also models should output Properties, not PropertyTypes?

**Comment by computron** [comment]
All this is part of a bigger comment which is that these graphs are way too complicated.

**Comment by mkhorton** [comment]
Honestly don't think the graphs are complicated! but maybe they're poorly explained right now.

The idea is that models are only connected to property types, this is our 'knowledge' of the model:

(input) Property Type --> Model --> (output) Property Type

To actually 'solve' the model, you have to add actual instances of Properties (i.e. an actual value), the graph then looks:

Property (input value) --> Property Type --> Model --> Property Type --> Property (output value)

The benefit of this approach is that the (Property Type --> Model --> Property Type) subgraph is *always* the same, so is easier to reason about and code for, and then actual property values can be composed into the graph.

This graph composition step is very easy: when defining a value, it links to a property type. Since there is one and only one instance of a given property type on the graph, the edges are added automatically by the composition algorithm.

> All this is part of a bigger comment which is that these graphs are way too complicated.

However, this is more broadly a project question. It's certainly possible to over-engineer this, and perhaps the benefits of engineering it this way will never be realized.

**Comment by mkhorton** [comment]
To rephrase (and the README could be re-worded to better explain this), there are actually two graphs:

* A 'master' graph, consisting of models and property types, that is always the same (this is what the diagram calls the 'logic layer')
* A 'material' graph, consisting of a material node, e.g. a formula, and values of certain properties for that material (this is what the diagram calls the 'data layer')

To solve, we compose the material graph into the master graph.

**Comment by dmrdjenovich** [comment]
Maybe we could have a more in-depth discussion on the structure of the graphs in the next TRI virtual meeting to hash things out? But as of now I agree that the graphs are as simple as I think they can be and there are still more features to add as was noted in other issues. In other words, I can't think of a simpler design. I also think that with encapsulation and appropriate interfaces we can mask complexity to the end user as necessary.
