### ISSUE TITLE
why do you need to add a material to propnet?

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#81]
in the example notebook, why do you need

p.add_material(silica)

Why can't you only have:

p.evaluate(material=silica)

without the first step?

**Comment by mkhorton** [comment]
I think the idea was you might want to add multiple materials to propnet, for models that take multiple materials as input.

I agree the latter is cleaner (and even for multiple materials, you could just have `p.evaluate(materials=[silica, ITO])` or something). It's a fairly small change anyway.

The other thing, is that I think `material.evaluate()` should also work, because I think this makes more sense to the end user (who might not care what `p` or propnet are -- "why do I need this propnet object?" etc.)

I agree we should follow the principle of least surprise here ...

**Comment by montoyjh** [comment]
This has been changed.  graph.evaluate now generates a new augmented material.
