### ISSUE TITLE
demo notebook: "creating _ at Runtime"

### ISSUE THREAD

**Issue by computron** [materialsintelligence/propnet#84]
Are these really being created at runtime? Or is this just a way for a user to write their own Symbol and Model classes?

Btw do these need to be "registered" with propnet at all?

**Comment by dmrdjenovich** [comment]
Yes importantly these are actually being created at runtime. This is important because in earlier implementations, all Models and Properties were loaded once at the beginning of the program, and you couldn't add more unless you exited the python shell and re-launched.

So allowing for creation at runtime can save the user from potentially having to re-run code / lose unsaved work. Yes they do need to be "registered" with propnet, but that can happen dynamically during runtime as well. 

So all in all there are 2 ways for the user to write their own Symbol and Model classes.

1) Make the appropriate .py and .yaml files BEFORE launching Propnet.
2) Make the classes at runtime and dynamically add them to the current Propnet instance.

**Comment by computron** [comment]
normally "creating classes at runtime" is associated with metaclasses, i.e. you are not writing out the entire class definition just later on in a notebook or something. Maybe a question of semantics to discuss w/ @mkhorton

**Comment by computron** [comment]
Just a quick FYI - the metaclass stuff would allow you to do something like read all your YAML files and then programmatically create a class for each YAML file. Thus, the number of classes would not (necessarily) be predictable in advance until you run your code which figures out how many YAML files there are and creates a Python class on the fly for each one.

Not saying you should actually do that, but just an example of what I would have considered "runtime class creation" - again just semantics tho

**Comment by montoyjh** [comment]
The demo notebooks needs to be rewritten generally, so I'm going to lump this in with #83 and attempt to address both these issues there.
